export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    agent_id TEXT NOT NULL,
    task_id TEXT,
    task_type TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    total_prompt_tokens INTEGER DEFAULT 0,
    total_response_tokens INTEGER DEFAULT 0,
    total_calls INTEGER DEFAULT 0,
    total_flags INTEGER DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS llm_calls (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    task_id TEXT,
    task_type TEXT,
    upstream_model TEXT,
    prompt_tokens INTEGER DEFAULT 0,
    response_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER DEFAULT 0,
    system_tokens INTEGER DEFAULT 0,
    tool_tokens INTEGER DEFAULT 0,
    memory_tokens INTEGER DEFAULT 0,
    history_tokens INTEGER DEFAULT 0,
    tool_output_tokens INTEGER DEFAULT 0,
    unknown_tokens INTEGER DEFAULT 0,
    request_hash TEXT,
    stable_prefix_hash TEXT,
    latency_ms INTEGER,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS context_flags (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    llm_call_id TEXT NOT NULL,
    flag_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    message TEXT NOT NULL,
    estimated_tokens_involved INTEGER,
    suggestion TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS repeated_blocks (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    llm_call_id TEXT NOT NULL,
    block_hash TEXT NOT NULL,
    occurrences INTEGER NOT NULL,
    estimated_tokens INTEGER NOT NULL,
    sample_preview TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tool_usage (
    id TEXT PRIMARY KEY,
    call_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    agent_id TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    shipped INTEGER NOT NULL DEFAULT 0,
    invoked INTEGER NOT NULL DEFAULT 0,
    description_tokens INTEGER DEFAULT 0,
    description_preview TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_llm_calls_run_id ON llm_calls(run_id)`,
  `CREATE INDEX IF NOT EXISTS idx_context_flags_run_id ON context_flags(run_id)`,
  `CREATE INDEX IF NOT EXISTS idx_context_flags_call_id ON context_flags(llm_call_id)`,
  `CREATE INDEX IF NOT EXISTS idx_repeated_blocks_run_hash ON repeated_blocks(run_id, block_hash)`,
  `CREATE INDEX IF NOT EXISTS idx_runs_agent ON runs(agent_id, started_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tool_usage_agent_time ON tool_usage(agent_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_tool_usage_call ON tool_usage(call_id)`,
];
